---
- name: Enable HTTP Auth
  hosts: "{{ web_environment }}"
  become: true
  vars_files:
    - var_files/web_vars.yml

  tasks:
    - name: Checking if config file exist in auth-available
      ansible.builtin.stat:
        path: "{{ AUTH_AVAILABLE }}/{{ site_url }}.conf"
      register: auth_available
      when:
        - site_url != ""

    - name: Checking if config file exist in auth-enabled
      ansible.builtin.stat:
        path: "{{ AUTH_ENABLED }}/{{ site_url }}.conf"
      register: auth_enabled
      when: auth_available.stat.exists == True

    - name: Progress
      ansible.builtin.debug:
        msg:
          - "Auth for {{ site_url }} already enabled"
          - "Other tasks will be skipped"
      when: auth_enabled.stat.exists == True

    - name: Add symlink in auth-enabled
      ansible.builtin.file:
        src: "{{ AUTH_AVAILABLE }}/{{ site_url }}.conf"
        dest: "{{ AUTH_ENABLED }}/{{ site_url }}.conf"
        state: link
      when: auth_enabled.stat.exists == False

    - name: Update vhost conf to enable HTTP Auth
      ansible.builtin.lineinfile:
        path: "{{ APACHE2_AVAILABLE }}/{{ site_url }}.conf"
        search_string: "Require all granted"
        line: "# Require all granted"
      when: auth_enabled.stat.exists == False

    - name: Read site metadata from persistent NFS store
      delegate_to: localhost
      run_once: true
      become: false
      ansible.builtin.command:
        cmd: "cat {{ SITE_LIST_PATH }}/{{ site_url }}.json"
      register: site_metadata_content
      failed_when: false
      changed_when: false
      when:
        - site_url != ""
        - auth_enabled.stat.exists == False

    - name: Parse and Update Metadata Facts
      ansible.builtin.set_fact:
        updated_metadata: >-
          {{
            (hostvars['localhost']['site_metadata_content'].stdout | from_json) | combine({
              'auth_status': 'enabled'
            })
          }}
      when:
        - site_url != ""
        - auth_enabled.stat.exists == False
        - hostvars['localhost']['site_metadata_content'].rc == 0

    - name: Save updated metadata back to persistent NFS store
      delegate_to: localhost
      run_once: true
      become: false
      ansible.builtin.copy:
        content: "{{ updated_metadata | to_nice_json }}"
        dest: "{{ SITE_LIST_PATH }}/{{ site_url }}.json"
        mode: "0644"
      when:
        - site_url != ""
        - auth_enabled.stat.exists == False
        - hostvars['localhost']['site_metadata_content'].rc == 0

    - name: Restart apache2
      ansible.builtin.systemd:
        name: apache2
        state: restarted
      when: auth_enabled.stat.exists == False
